### ISSUE TITLE
Pypi package broken

### ISSUE THREAD

**Issue by susundberg** [chintal/fpv-gcc#1]
Hi!

I just installed this from pip: 
```
pip install fpvgcc
Collecting fpvgcc
  Downloading fpvgcc-0.7.9-py2-none-any.whl
Collecting six (from fpvgcc)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting prettytable (from fpvgcc)
  Downloading prettytable-0.7.2.zip
Requirement already satisfied: wheel in /home/HHHH/XXX/ENV_PLATFORMIO/lib/python2.7/site-packages (from fpvgcc)
Building wheels for collected packages: prettytable
  Running setup.py bdist_wheel for prettytable ... done
  Stored in directory: /home/HHHH/.cache/pip/wheels/b6/90/7b/1c22b89217d0eba6d5f406e562365ebee804f0d4595b2bdbcd
Successfully built prettytable
Installing collected packages: six, prettytable, fpvgcc
Successfully installed fpvgcc-0.7.9 prettytable-0.7.2 six-1.11.0
```

And after that running the binary with --help fails:
```
fpvgcc --help
Traceback (most recent call last):
  File "/home/HHHH/XXX/ENV_PLATFORMIO/bin/fpvgcc", line 7, in <module>
    from fpvgcc.cli import main
  File "/home/HHHH/XXX/ENV_PLATFORMIO/local/lib/python2.7/site-packages/fpvgcc/cli.py", line 29, in <module>
    from .fpv import process_map_file
  File "/home/HHHH/XXX/ENV_PLATFORMIO/local/lib/python2.7/site-packages/fpvgcc/fpv.py", line 28, in <module>                                                             
    from .gccMemoryMap import GCCMemoryMap, MemoryRegion                                                                                                                        
  File "/home/HHHH/XXX/ENV_PLATFORMIO/local/lib/python2.7/site-packages/fpvgcc/gccMemoryMap.py", line 23, in <module>                                                    
    from fpvgcc.datastructures.ntreeSize import SizeNTree, SizeNTreeNode                                                                                                        
ImportError: No module named datastructures.ntreeSize                       
```

**Comment by chintal** [comment]
@susundberg Sorry about that. I've fixed the setup.py and pushed a new version to PyPI. (Hopefully) It should work now.

**Comment by chintal** [comment]
Closing the issue. Please create a new one if you continue to have trouble.
